#!/bin/bash

set -e

#
# Must be run with -t:
#
# for example:
# qsub -t 1-10 -v DATABASE=gg135.97_otus.udb,IDENTITY=0.97,UC_FILE=test.97.uc usearch_array.qsub
#

#PBS -q submit
#PBS -M adavisr@ufl.edu
#PBS -m abe
#PBS -l mem=600mb
#PBS -l walltime=00:20:00
#PBS -l nodes=1:ppn=1
#PBS -N usearch-array
#PBS -M adavisr@ufl.edu
#PBS -j oe

QUERY="chunk-${PBS_ARRAYID}.fasta"

echo "started     => $(date)"
echo "job id      => $PBS_JOBID"
echo "query       => $QUERY"
echo "identity    => $IDENTITY"
echo "output (uc) => $UC_FILE"
echo "database    => $DATABASE"

cd $PBS_O_WORKDIR

usearch \
  --usearch_local $QUERY \
  --id $IDENTITY \
  --uc $UC_FILE \
  --strand plus \
  --threads 1 \
  --db $DATABASE

touch $QUERY.completed
