#!/bin/bash

time python hiseq_pipe/__main__.py demultiplex \
  --left-reads test/data/test_left.fastq.gz \
  --barcode-reads test/data/test_bc.fastq.gz \
  --right-reads test/data/test_right.fastq.gz \
  --barcodes data/triplett-barcodes.csv \
  --bc-seq-proc 'lambda k: k[0:7]' \
  --revcomp \
  --gzip \
  --id-format 'test-%(barcode)s-%(index)s' \
  --output /dev/null
