#!/bin/bash

python hiseq_pipe/__main__.py demultiplex \
  --left-reads test/data/test_left.fastq \
  --barcode-reads test/data/test_bc.fastq \
  --right-reads test/data/test_right.fastq \
  --barcodes test/data/test_barcodes.csv \
  --bc-seq-proc 'lambda k: k[0:7]' \
  --revcomp \
  --output /dev/null
