#!/bin/bash

set -e

test_files=$(find test -type f -perm +111 -print)

START=$(date +%s)

for test in $test_files; do
  echo "- RUNNING TEST: $test"
  $test

  echo
done

STOP=$(date +%s)

echo "Ran ${#test_files[@]} tests in $(($STOP - $START)) seconds."
